/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/bm96OfWpiMX
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
'use client';

import { Avatar, AvatarImage, AvatarFallback } from '@/components/ui/avatar';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
} from '@/components/ui/dropdown-menu';
import { Sheet, SheetTrigger, SheetContent } from '@/components/ui/sheet';
import { Film, ListFilter, Menu, Sun } from 'lucide-react';
import Link from 'next/link';
import { useState } from 'react';

export default function MoviesPage() {
  const [isDarkMode, setIsDarkMode] = useState(false);
  const [_, setIsDrawerOpen] = useState(false);
  const movies = [
    {
      id: 'tt0111161',
      name: 'The Shawshank Redemption',
      description:
        'Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion.',
      cast: ['Tim Robbins', 'Morgan Freeman'],
      certificate: 'R',
      genres: ['Drama'],
      image: {
        url: 'https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_.jpg',
        width: 1200,
        height: 1800,
      },
      rank: 1,
      ratingsSummary: {
        aggregateRating: 9.3,
        voteCount: 2865906,
      },
      releaseYear: 1994,
      runtime: 8520,
      tagline: 'Fear can hold you prisoner. Hope can set you free.',
      isFeatured: false,
    },
    {
      id: 'tt0068646',
      name: 'The Godfather',
      description:
        'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
      cast: ['Marlon Brando', 'Al Pacino'],
      certificate: 'R',
      genres: ['Crime', 'Drama'],
      image: {
        url: 'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg',
        width: 1396,
        height: 1982,
      },
      rank: 2,
      ratingsSummary: {
        aggregateRating: 9.2,
        voteCount: 1996320,
      },
      releaseYear: 1972,
      runtime: 10500,
      tagline: "An offer you can't refuse.",
      isFeatured: false,
    },
    {
      id: 'tt0468569',
      name: 'The Dark Knight Rises: The Epic Conclusion to the Legendary Batman Trilogy',
      description:
        'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
      cast: ['Christian Bale', 'Heath Ledger'],
      certificate: 'PG-13',
      genres: ['Action', 'Crime', 'Drama'],
      image: {
        url: 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg',
        width: 1383,
        height: 2048,
      },
      rank: 3,
      ratingsSummary: {
        aggregateRating: 9,
        voteCount: 2847398,
      },
      releaseYear: 2008,
      runtime: 9120,
      tagline: 'Why So Serious?',
      isFeatured: false,
    },
  ];
  return (
    <div
      className={`flex min-h-screen flex-col p-4 ${isDarkMode ? 'dark' : ''}`}
    >
      <header className="flex items-center justify-between border-b pb-4 dark:border-muted">
        <Sheet>
          <SheetTrigger asChild>
            <button
              className={`rounded-full p-2 transition-colors sm:hidden ${
                isDarkMode
                  ? 'bg-primary text-primary-foreground hover:bg-primary/90'
                  : 'bg-muted text-muted-foreground hover:bg-muted/90'
              }`}
              onClick={() => {
                setIsDrawerOpen(true);
              }}
            >
              <Menu className="size-6" />
            </button>
          </SheetTrigger>
          <SheetContent className="w-[300px] p-4" side="left">
            <div className="flex items-center space-x-4">
              <Film className="size-6" />
              <h1 className="text-xl font-bold">Movie Magic</h1>
            </div>
            <nav className="mt-6 flex flex-col space-y-4">
              <Link className="font-medium" href="#" prefetch={false}>
                Movies
              </Link>
              <Link className="font-medium" href="#" prefetch={false}>
                Watchlist
              </Link>
            </nav>
          </SheetContent>
        </Sheet>
        <div className="hidden items-center space-x-4 sm:flex">
          <div className="flex items-center space-x-4">
            <Film className="size-6" />
            <h1 className="text-xl font-semibold">Movie Magic</h1>
          </div>
          <nav className="flex items-center space-x-4">
            <Link className="font-medium" href="#" prefetch={false}>
              Movies
            </Link>
            <Link className="font-medium" href="#" prefetch={false}>
              Watchlist
            </Link>
          </nav>
        </div>
        <div className="ml-auto flex items-center space-x-4">
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <button
                className={`rounded-full p-2 transition-colors ${
                  isDarkMode
                    ? 'bg-primary text-primary-foreground hover:bg-primary/90'
                    : 'bg-muted text-muted-foreground hover:bg-muted/90'
                }`}
              >
                <div>
                  <Sun className="size-6" />
                </div>
              </button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" className="w-40">
              <DropdownMenuItem
                onClick={() => {
                  setIsDarkMode(false);
                }}
              >
                Light
              </DropdownMenuItem>
              <DropdownMenuItem
                onClick={() => {
                  setIsDarkMode(true);
                }}
              >
                Dark
              </DropdownMenuItem>
              <DropdownMenuItem
                onClick={() => {
                  setIsDarkMode(true);
                }}
              >
                System
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Avatar>
                <AvatarImage alt="User Avatar" src="/placeholder-user.jpg" />
                <AvatarFallback>U</AvatarFallback>
              </Avatar>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" className="w-60">
              <DropdownMenuLabel>
                <div className="font-semibold">John Doe</div>
                <div className="text-sm text-muted-foreground">
                  john@example.com
                </div>
              </DropdownMenuLabel>
              <DropdownMenuSeparator />
              <DropdownMenuItem>Sign Out</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </header>
      <main className="mt-4 flex flex-1 flex-col gap-4">
        <div className="flex items-center justify-between">
          <Sheet>
            <SheetTrigger asChild>
              <Button className="flex items-center space-x-2" variant="outline">
                <span>Filter & Sort</span>
                <ListFilter className="size-4" />
              </Button>
            </SheetTrigger>
            <SheetContent className="w-[300px] p-4" side="left">
              Filter & Sort
            </SheetContent>
          </Sheet>
          <Badge variant="secondary">250 Movies</Badge>
        </div>
        <header className="sticky top-14 z-50 hidden w-full border-b bg-background sm:top-28 sm:block">
          <div className="flex items-center gap-x-3 px-2 py-3 text-sm leading-none text-muted-foreground">
            <div className="mr-2 hidden w-8 shrink-0 text-right sm:block">
              #
            </div>
            <div className="w-16 flex-1 shrink-0 ">Title</div>
            <div className="hidden w-12 shrink-0 text-center sm:block">
              Rating
            </div>
            <div className="hidden w-12 shrink-0 text-right sm:block">Year</div>
            <div className="hidden w-12 shrink-0 text-right sm:block">
              Runtime
            </div>
          </div>
        </header>
        {movies.map((movie) => (
          <div
            className="flex items-center gap-x-3 rounded-md p-2 text-sm text-muted-foreground hover:bg-muted/50"
            key={movie.id}
          >
            <div className="mr-2 hidden w-8 shrink-0 text-right text-base sm:block">
              {movie.rank}
            </div>
            <div className="relative flex h-24 w-16 shrink-0 overflow-hidden rounded-md">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                alt={movie.name}
                className="aspect-[2/3] w-full object-cover"
                height={movie.image.height}
                src="/placeholder.svg"
                width={movie.image.width}
              />
            </div>
            <div className="mr-6 min-w-0 flex-1 overflow-hidden">
              <p className="line-clamp-2 text-base leading-5 text-accent-foreground">
                {movie.name}
              </p>
              <div className="flex items-center gap-x-1">
                {movie.genres.join(', ')}
              </div>
            </div>
            <div className="hidden w-12 shrink-0 text-center sm:block">
              {movie.certificate}
            </div>
            <div className="hidden w-12 shrink-0 text-right sm:block">
              {movie.releaseYear}
            </div>
            <div className="hidden w-12 shrink-0 text-right sm:block">
              {movie.runtime}
            </div>
          </div>
        ))}
      </main>
    </div>
  );
}
